name: Terraform Azure Destruction

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Terraform Backend
        run: |
          terraform init -backend-config="resource_group_name=StorageRG" -backend-config="storage_account_name=taskboardstorage" -backend-config="container_name=taskboardcontainer" -backend-config="key=terraform.tfstate"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
